In [2]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 示例用法
ngram_sequences = [['This', 'is', 'an'], ['is', 'an', 'example'], ['an', 'example', 'sentence'], ['example', 'sentence', 'for'], ['sentence', 'for', 'n-gram'], ['for', 'n-gram', 'generation.']]

# 使用词袋模型表示
count_vectorizer = CountVectorizer()
count_vectors = count_vectorizer.fit_transform([' '.join(seq) for seq in ngram_sequences])
print(count_vectors.toarray())

# 使用TF-IDF表示
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectors = tfidf_vectorizer.fit_transform([' '.join(seq) for seq in ngram_sequences])
print(tfidf_vectors.toarray())

['This is an', 'is an example', 'an example sentence', 'example sentence for', 'sentence for n-gram', 'for n-gram generation.']
[[1 0 0 0 0 1 0 1]
 [1 1 0 0 0 1 0 0]
 [1 1 0 0 0 0 1 0]
 [0 1 1 0 0 0 1 0]
 [0 0 1 0 1 0 1 0]
 [0 0 1 1 1 0 0 0]]
[[0.47196441 0.         0.         0.         0.         0.55902156
  0.         0.68172171]
 [0.54209195 0.54209195 0.         0.         0.         0.64208461
  0.         0.        ]
 [0.57735027 0.57735027 0.         0.         0.         0.
  0.57735027 0.        ]
 [0.         0.57735027 0.57735027 0.         0.         0.
  0.57735027 0.        ]
 [0.         0.         0.54209195 0.         0.64208461 0.
  0.54209195 0.        ]
 [0.         0.         0.47196441 0.68172171 0.55902156 0.
  0.         0.        ]]


In [2]:
# print([2:8])
# print from 2 to 8
import numpy as np
print(np.arange(10)[2:8])


[2 3 4 5 6 7]
